### ISSUE TITLE
Accents problem, wrong charset maybe

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [rianjs/ical.net#534]
Hi, I'm working with multiple languages, which includes accents
So when Inputing srtrings with accents they get the wrong Output

Here it is the generated ICS sample:
`BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:America/Sao_Paulo
X-LIC-LOCATION:America/Sao_Paulo
BEGIN:STANDARD
DTSTART:20190217T000000
RRULE:FREQ=YEARLY;BYDAY=3SA;BYMONTH=2
TZNAME:-03
TZOFFSETFROM:-0200
TZOFFSETTO:-0300
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;RSVP=FALSE;CN=Daniel:mailto:Daniel@Daniel.com.br
ATTENDEE;RSVP=FALSE;CN=Genildo:mailto:genildo@email.com
ATTENDEE;RSVP=FALSE;CN=Robervaldo:mailto:
DTEND:20211029T200000Z
DTSTAMP:20211028T131335Z
DTSTART:20211029T110000Z
LOCATION:Escrit?rio Sorocaba - 2? Andar / Sala de Reuni?o Megan Fox
ORGANIZER;CN=Velari Administrador:mailto:daniel.scatigno@ncpc.com.br
SEQUENCE:0
STATUS:Confirmado
SUMMARY:Envio de e-mail para Concierge
UID:d9f4a842-9c5e-4642-8509-85a5a1581c7e
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR`

the Location should be:
LOCATION:Escritório Sorocaba - 2º Andar / Sala de Reunião Megan Fox

How can I fix that?

**Comment by jorgesomers** [comment]
Hi @danielscatigno-ncpc,

Have you tried to encode the text ?
