### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by manolod** [rianjs/ical.net#539]
Hi,
language : C# dotnet core.
Visual studio 2022
OS : Windows 11

trying to parse this ical  crashes the parser with error : Unable to cast object of type 'System.String' to type 'System.TimeSpan'.
Stack trace:
   at Ical.Net.Serialization.DataTypes.TriggerSerializer.Deserialize(TextReader tr)
   at Ical.Net.Serialization.SimpleDeserializer.SetPropertyValue(SerializationContext context, CalendarProperty property, String value)
   at Ical.Net.Serialization.SimpleDeserializer.ParseContentLine(SerializationContext context, String input)
   at Ical.Net.Serialization.SimpleDeserializer.<Deserialize>d__11.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__61`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Ical.Net.CalendarCollection.Load(TextReader tr)

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:hidden@hidden.com
X-WR-TIMEZONE:America/Santiago
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Araguaina
X-LIC-LOCATION:America/Araguaina
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:-03
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Monterrey
X-LIC-LOCATION:America/Monterrey
BEGIN:DAYLIGHT
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
TZNAME:CDT
DTSTART:19700405T020000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
TZNAME:CST
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Santiago
X-LIC-LOCATION:America/Santiago
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0400
TZNAME:-04
DTSTART:19700405T000000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:-0400
TZOFFSETTO:-0300
TZNAME:-03
DTSTART:19700906T000000
RRULE:FREQ=YEARLY;BYMONTH=9;BYDAY=1SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DTSTART:20160920T150000Z
DTEND:20160920T160000Z
DTSTAMP:20210824T183619Z
UID:570213ce-cdf0-43b7-9b23-fbdea5d58ba4
CREATED:20210824T171549Z
DESCRIPTION:N°Cita: 0059013573 Profesional: hidden hidden\, hidden Mari
 a Especialidad: Medicina General
LAST-MODIFIED:20210824T183619Z
LOCATION:aaaaaaaaaaaaa aaaaa Egaña aaaaaaa aaaaaaa 1111\, aa aaaaa\,  AAAAA
 AAAA AAAA 06
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Atención Médica
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H10M0S
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:20160920T100000
DESCRIPTION:Atención Médica
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by Idrek** [comment]
I think you have to reflect explicitly that an absolute trigger is a `datetime`. Otherwise it tries to parse it as a duration (`timespan`). So, try to change the following line:

`TRIGGER:20160920T100000`

with

`TRIGGER;VALUE=DATE-TIME:20160920T100000`

**Comment by manolod** [comment]
We are parsing a calendar entry found in our GMail calendar.
You suggestion is that if we're getting this exception, we should try to read the Ical as plain text, check if we have this invalid trigger definition and patch it?

**Comment by Idrek** [comment]
According to the [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.6.3), or at least as i understand the following sentence:

> Value Type:  The default value type is DURATION.  The value type can be set to a DATE-TIME value type, in which case the value MUST specify a UTC-formatted DATE-TIME value.

The entry from GMail doesn't seem to adapt to the standard, which is weird. Sure you could pre-process the calendar in plain text to detect and fix them before calling ical.net, but it will depend in your infrastructure how easy or hard it can be.
