### ISSUE TITLE
Framework 2 or 5

### ISSUE THREAD

**Issue by WGGWSys** [rianjs/ical.net#546]
Dear rianjs,

I found Your iCal in Github, thank you for sharing it with others!

You wrote it for Frameworks 2.0 and 5.0 and now I have the problem,
that I don't want to switch my project to 2.0 because of Lib-Functions
wanting 3.5 and not to 5.0 because of "too new for some".

Up to now I always had Libraries, working with "we need FW x.y as a
minimum" -including DevXpress- so that I don't know how to include
your Lib. 
I included a <TargetFrameworks>net20;net40</TargetFrameworks> to my
Project File, but it did not work. I also tried netstandard2.0 there,
same result.

It would be fine, if you had a tip, how to run your library
in a project targetting Framework 3.5 or 4.0.

Thanks and best regards

**Comment by art-ist** [comment]
@WGGWSys  It's actually not Framework 2.0. It's .NET Standard 2.0. See the supported Frameworks here [https://www.nuget.org/packages/Ical.Net#supportedframeworks-tab].

I target .NET Framweork 4.8 and it works fine.

If you agree, that issue could be closed.
