### ISSUE TITLE
Time Zone ends as UTC on notification

### ISSUE THREAD

**Issue by steverzag** [rianjs/ical.net#558]
I'm trying to send an appointment notification, this is the ics file I get from the code

BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:America/Chicago
X-LIC-LOCATION:America/Chicago
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=Help Desk;PARTSTAT=ACCEPTED;RSVP=FALSE;ROLE=REQ-PARTICIPANT;CU
 TYPE=INDIVIDUAL:mailto:helpdesk@example.com
DESCRIPTION:
DTEND;TZID=America/Chicago:20220912T053000
DTSTAMP:20220829T201033Z
DTSTART;TZID=America/Chicago:20220909T173000
LOCATION:https://www.gotomeet.me/example
ORGANIZER;CN=Devone Torrence:mailto:user@example.com
SEQUENCE:0
SUMMARY:SmartTouch Support
TRANSP:TRANSPARENT
UID:3d4c1226-df73-4c3f-afbf-89be9e5e7ff7
END:VEVENT
END:VCALENDAR

Im preatty sure we are doing what the documentation suggest on Time Zone , but for some reason the date is showing up as UTC time on the notification, same scenario wheher is outlook or gmail. 

![Screenshot 2022-10-06 123233](https://user-images.githubusercontent.com/46872032/194369619-52e9167b-2673-4009-9883-6be18c38df36.png)

We have the same feature with others prodId and works fine, is on ical when it has this behavior. Any light some one can throw over this is welcome. Thanks in advance.

**Comment by bhupinder7** [comment]
Did you resolve this issue? I am having the same problem

**Comment by steverzag** [comment]
Hi there,

Unfortunately not. It's a remaining task on my agenda.

Regards.
