### ISSUE TITLE
Modify a Recurring/occurrence Instance

### ISSUE THREAD

**Issue by jayesh14** [rianjs/ical.net#563]
Hello team, 

I want to update one instance (datetime) from recurring/occurrence.
Can you please share any example with iCal.net ?  Any suggestion ?

Thanks

**Comment by axunonb** [comment]
As there hasn’t been any recent activity on this issue, I’m going to close it for now. If anyone still encounters this problem or has additional information to share, please feel free to reopen the issue or create a new one.
Please double-check with the latest release.
