### ISSUE TITLE
GetOccurrences Creates event with invalid time due to Daylight Savings changes

### ISSUE THREAD

**Issue by cyberjared** [rianjs/ical.net#567]
Sample code to duplicate:

`var calStart = new CalDateTime(DateTimeOffset.Parse("2023-01-14T19:21:03.700Z").UtcDateTime, "UTC");
			var calFinish = new CalDateTime(DateTimeOffset.Parse("2023-03-14T18:21:03.700Z").UtcDateTime, "UTC");
			var tz = "Pacific Standard Time";
			var pattern = new RecurrencePattern("FREQ=WEEKLY;BYDAY=SU,MO,TU,WE");
			//Adjust the date to today so that the times remain constant
			DateTime localTZstartAdjust = DateTools.CombineDateTimes(DateTime.Now, TimeSpan.FromHours(2).Add(TimeSpan.FromMinutes(35)));
			DateTime localTZfinishAdjust = DateTools.CombineDateTimes(DateTime.Now, TimeSpan.FromHours(17));
			var ev = new Ical.Net.CalendarComponents.CalendarEvent {
				Class = "PUBLIC",
				IsAllDay = false,
				Start = new CalDateTime(localTZstartAdjust, tz),
				End = new CalDateTime(localTZfinishAdjust, tz),
				Sequence = 0,
				RecurrenceRules = new List<RecurrencePattern> { pattern }
			};
			var col = ev.GetOccurrences(calStart, calFinish);
			`

col will include an event that starts at 2:35 am on March 12, 2023 PST, but that time doesn't exist since this is when the time changes.

**Comment by axunonb** [comment]
Related to #660
