### ISSUE TITLE
Natural Language de/serialization

### ISSUE THREAD

**Issue by paviad** [rianjs/ical.net#576]
A very desirable feature of this library, and which exists in similar libraries in other languages (e.g. [Typescript's Equivalent](https://github.com/jakubroztocil/rrule) is the ability to serialize and deserialize to and from natural language, for example:

`Every day at 10, 12 and 17` should deserialize into `FREQ=DAILY;BYHOUR=10,12,17`

and vice versa.

I think this should be implemented as a separate (and optional) NuGet package.

**Comment by paviad** [comment]
I also have made an Antlr4 parser - I think it is better, easier to reason about the parsing (and also to maintain/modify)

**Comment by axunonb** [comment]
@minichma There are 2 different aspects mentioned:
1. Natural language: Not a high priority feature, and should go into an extension package
2. Replace Regex with a Parser: A valid point regarding performance, memory allocations, maintainability. At NCalc we're using [Parlot](https://github.com/sebastienros/parlot) - unfortunately no experience on my side.

How to deal with this issue?

**Comment by minichma** [comment]
Ad 1) I'm really not the right one to comment on that as it is strongly tied to the future strategy of this project. At this time I feel that addressing existing issues would be a number one priority and is enough work for a while. So adding new features would not be too helpful for that as someone will have to work on it and, more notably, maintain it in the future. But this could also be maintained in a separate repo. @paviad would it be an option for you to publish this as an independent package in a separate repo?

Ad 2) Are we talking about a parser for the new feature (natural language) or for ical.net as a whole. @paviad I assume the first, right? Then its tied to 1. The ical.net parser seems to be rather stable, but if an alternative existed in the form of a PR, I would assume it would be welcome.

**Comment by paviad** [comment]
Can I use the name *Ical.Net.NaturalLanguage* ?

**Comment by axunonb** [comment]
@paviad The name would be fine - maybe a bit long. Sth. shorter like `ICal.Net.Phrases`...? This was a co-pilot suggestion :)
If you like, we can create the repo under `ical-org` (GitHub organization) to strengthen the "brand" with you as maintainer or admin.

**Comment by axunonb** [comment]
@minichma 
>  I feel that addressing existing issues would be a number one priority and is enough work for a while

Fully agree

> the future strategy of this project

Making ICal.Net the best in class for dot net - in terms of usability, performance and RFC compliance / compatibility

**Comment by minichma** [comment]
> Making ICal.Net the best in class for dot net - in terms of usability, performance and RFC compliance / compatibility

Great mission statement! Should be added to the readme.

**Comment by philsayersCDS** [comment]
Maybe you could leverage this library for generating natural language from a cron expression: 
https://github.com/Humanizr/Humanizer

**Comment by paviad** [comment]
I have a complete NL solution, but we can talk about extending it to more grammars later.

**Comment by paviad** [comment]
Done https://github.com/paviad/ical.net.naturallanguage and published on NuGet https://www.nuget.org/packages/Ical.Net.NaturalLanguage/

**Comment by axunonb** [comment]
Ah, congratulations! All the work is already done. Will have a closer look shortly.
So we can close the issue, right?

**Comment by paviad** [comment]
I believe so, closing :)
