### ISSUE TITLE
AddTimeZone(string, DateTime, bool) fails if the DateTime parameter is a leap day (February 29)

### ISSUE THREAD

**Issue by st-abarker** [rianjs/ical.net#583]
When trying to exclude historical data from a time zone being added to a calendar object, providing a leap day for earliestDateTimeToSupport causes an exception indicating an invalid date. This appears to be due to the way the method calculates the date for one year prior to the provided earliestDateTimeToSupport.

**Comment by fatimaatharkhan** [comment]
Is this project actively being worked on as I want to contribute to it. If yes, can you please assign a good first issue to me in this project? I am a junior, completing my Bachelor's degree in CS and this will be my first contribution.

**Comment by axunonb** [comment]
Closed with #595
