### ISSUE TITLE
Sync issue with Outlook 365 Calendar

### ISSUE THREAD

**Issue by stefancvetkovic** [rianjs/ical.net#586]
Hello,
Im using my .net core custom app  and I am generating a webcal link (ical) for subscribing it from Outlook 365.
Initial subscription goes wel, all items are imported into Outlook365, but when I change some item in my app, it doesn't reflect to Outlook365.
Do you maybe across to same issue? Any hints what should I try? Thanks

**Comment by axunonb** [comment]
Please double-check the new version merged with #595
