### ISSUE TITLE
Crash on Google ics

### ISSUE THREAD

**Issue by Eddy1204** [rianjs/ical.net#593]
Hello,
If I read an ics file that was created by Google, the file is read successfully in debug mode.
But if I start the program in release, the function crashes when reading.

var calendar = Calendar.Load(ics_string);

Is there anything else I need to consider beforehand?

**Comment by axunonb** [comment]
Please provide some working sample code, that can be used to reproduce the described behavior.

**Comment by axunonb** [comment]
We're closing this issue. Feel free to re-open when some working sample code, that can be used to reproduce the described behavior is available.
