### ISSUE TITLE
Evaluate some tests failing from the libical test suite.

### ISSUE THREAD

**Issue by minichma** [rianjs/ical.net#618]
When running a [list of test cases](https://github.com/libical/libical/blob/cfd401b9d043214395888de1d9daf52263e3245b/src/test/icalrecur_test.out) from [the libical project](https://github.com/libical/libical), the following tests fail. The reason should be investigated.

- [x] `DTSTART:20120101T120000`, `RRULE:FREQ=YEARLY;BYYEARDAY=-366;COUNT=3`
  Values differ at index [1]
  Expected: <01.01.2016 12:00:00 UTC>
  But was:  <31.12.2012 12:00:00 UTC>

- [x] `DTSTART:20121231T120000`, `RRULE:FREQ=YEARLY;BYYEARDAY=366;COUNT=3`
    Values differ at index [1]
    Expected: <31.12.2016 12:00:00 UTC>
    But was:  <01.01.2014 12:00:00 UTC>

- [x] `DTSTART:20121231T120000`, `RRULE:FREQ=YEARLY;BYYEARDAY=366;UNTIL=20200101T000000`
   Values differ at index [1]
   Expected: <31.12.2016 12:00:00 UTC>
   But was:  <01.01.2014 12:00:00 UTC>

- [x] `DTSTART:20130101T000000`, `RRULE:FREQ=YEARLY;BYWEEKNO=1,2,-1,-2;BYDAY=TU;UNTIL=20170101T000000Z`
    Fixed in #654
    System.ArgumentOutOfRangeException : The added or subtracted value results in an un-representable DateTime. (Parameter 'value')
    DateTime.ThrowDateArithmetic(Int32 param)
    DateTime.AddTicks(Int64 value)
    RecurrencePatternEvaluator.GetWeekNoVariants(List`1 dates, RecurrencePattern pattern, Nullable`1 expand) line 425

- [x] `DTSTART:20141006T090000`, `RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=2;BYDAY=MO;`
    Fixed in #645
    System.IndexOutOfRangeException : Index was outside the bounds of the array.
    RecurrencePatternSerializer.Deserialize(TextReader tr) line 244

- [x] `DTSTART:20161229T090000`, `RRULE:FREQ=WEEKLY;UNTIL=20170127T000000Z;WKST=MO;BYDAY=SU,TU,TH;INTERVAL=2`
    Fixed in #645
    Expected is <System.Collections.Generic.List`1[Ical.Net.DataTypes.CalDateTime]> with 6 elements, actual is <System.Collections.Generic.List`1[Ical.Net.DataTypes.IDateTime]> with 7 elements
    Values differ at index [1]
    Expected: <10.01.2017 09:00:00 UTC>
    But was:  <03.01.2017 09:00:00 UTC>

- [x] `DTSTART:20180206T080001`, `RRULE:FREQ=YEARLY;BYWEEKNO=6;BYDAY=TU;WKST=TH;UNTIL=20210612T000000Z`
    Fixed in #652
    Expected is <System.Collections.Generic.List`1[Ical.Net.DataTypes.CalDateTime]> with 4 elements, actual is <System.Collections.Generic.List`1[Ical.Net.DataTypes.IDateTime]> with 3 elements
    Values differ at index [0]
    Expected: <13.02.2018 08:00:01 UTC>
    But was:  <06.02.2018 08:00:01 UTC>

- [x] `DTSTART:20241018`, `RRULE:FREQ=DAILY;BYMINUTE=1,2,3,4;INTERVAL=2;COUNT=3`
  Fixed by #619 
    Expected is <System.Collections.Generic.List`1[Ical.Net.DataTypes.CalDateTime]> with 3 elements, actual is <System.Collections.Generic.List`1[Ical.Net.DataTypes.IDateTime]> with 3 elements
    Values differ at index [0]
    Expected: <18.10.2024 UTC>
    But was:  <18.10.2024 00:01:00 UTC>

Also see #617

**Comment by axunonb** [comment]
This is a brilliant source to improve the code (and a brilliant idea, of course).
