### ISSUE TITLE
High CPU consumption from v4.2.0 -> v4.3.1

### ISSUE THREAD

**Issue by TruDan** [rianjs/ical.net#628]
Hi,

Not really sure what changed (i tried looking through your changes between the two versions but there is a lot). however we have observed that after upgrading to v4.3.1 in our service, our average cpu usage goes from 0.1% -> 5% then gradually increasing over time to 80%.

We don't do any continious operations, its mostly loading an ical from a database, processing the occurences around the current date +- 1 week, and dispose. but then 1000's of times per minute.

It's almost like there is some kind of CPU leak, or threadpool leak in the newer version

**Comment by axunonb** [comment]
@TruDan  Out of curiosity: Would you share the cause of this issue? A lot (or endless number) of recurrences would have been my first guess...

**Comment by TruDan** [comment]
@axunonb turned out to be our own code causing it. From initial investigations it seemed to only happen with the newer version, but after letting it run for a while it still happened even with the old version. So it was just a coincidence that it was happening quicker with the newer version. After profiling etc it was actually our own code slowing down the whole application.. Oops, its now fixed and no complaints
