### ISSUE TITLE
Remove `UTF7Encoding`

### ISSUE THREAD

**Issue by axunonb** [rianjs/ical.net#649]
`UTF7Encoding.UTF7Encoding()` [is obsolete:](https://aka.ms/dotnet-warnings/SYSLIB0001) 
The UTF-7 encoding is insecure and should not be used. Use UTF-8 instead.
@minichma Agree?

**Comment by minichma** [comment]
Aside from security, in RFC 5545 I don't see any reference to 7-bit encoding, only `8BIT` and `BASE64`, so yes, I'd agree.

```
encodingparam      = "ENCODING" "="
                          ( "8BIT"
          ; "8bit" text encoding is defined in [[RFC2045](https://www.rfc-editor.org/rfc/rfc2045)]
                          / "BASE64"
          ; "BASE64" binary encoding format is defined in [[RFC4648](https://www.rfc-editor.org/rfc/rfc4648)]
```
